Easy fix: Not collected submission counts towards progress bar
MarkUsProject/Markus pull request #4854
Opened 2020-09-17 20:39 UTC by ANUSHIYAPRIYA

## Motivation and Context
This resolves issue #4502 

## Your Changes

**Description**:
Made changes so that the progress bar in the results page will display [ No.of submissions completed/No of. submissions collected ] ( Ex: 12/15 completed, where 15 - No of submissions collected )

**Type of change** (select all that apply):

 

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Refactoring (internal change to codebase, without changing functionality)
- [ ] Test update (change that modifies or updates tests only)
- [ ] Other (please specify): 

## Testing

Manually tested in the UI
Added corresponding tests for the changes

## Questions and Comments (if applicable)

## Checklist

- [x] I have performed a self-review of my own code.
- [ ] I have fixed any Hound bot comments. 
- [ ] I have verified that the TravisCI tests have passed. 
- [ ] I have reviewed the test coverage changes reported on Coveralls. 
- [x] I have added tests for my changes. 
- [ ] I have updated the Changelog.md file. 

### Required documentation changes (if applicable)

2020-09-18 16:51 UTC, mishaschwartz requested changes

2020-09-18 16:51 UTC, mishaschwartz commented on app/assets/javascripts/Components/Result/result.jsx
> +          num_collectd={this.props.num_collected}
- this prop is not used
- a prop named `num_collected` is already being passed to the `SubmissionSelector` on line 499
- `num_collected` should be accessed from the `this.state`, not `this.props` (see other comment below)

2020-09-18 16:51 UTC, mishaschwartz commented on app/assets/javascripts/Components/Result/result.jsx
>            num_assigned={this.state.num_assigned}
- `num_assigned` should no longer be necessary, remove it here and everywhere else

2020-09-18 16:51 UTC, mishaschwartz commented on app/views/results/edit.html.erb
> +  <% ta_id = @current_user.admin? ? nil : @current_user.id %>
don't define unnecessary variables in views

2020-09-18 16:51 UTC, mishaschwartz commented on app/views/results/edit.html.erb
> +          num_collected: <%= @assignment.get_num_collected(ta_id) %>,
this shouldn't be passed as a prop. Instead, get the information when setting the `state` of the Result component.

2020-09-23 13:29 UTC, mishaschwartz commented on app/controllers/results_controller.rb
>            data[:num_assigned] = assignment.get_num_assigned(current_user.admin? ? nil : current_user.id)
If `num_assigned` is not being used please remove it here as well.
If `get_num_assigned` is not being used anywhere else please remove that function as well.

2020-09-23 13:32 UTC, mishaschwartz approved these changes

2020-09-25 17:01 UTC, merged

2020-09-25 17:02 UTC, david-yz-liu commented
@ANUSHIYAPRIYA I merged this in because it fixes this specific issue, but it seems like there are other places in the code that still use `get_num_assigned` where it might be more appropriate to use `get_num_collected` instead. So could you please review those places as well?

2020-09-25 17:41 UTC, ANUSHIYAPRIYA commented
> @ANUSHIYAPRIYA I merged this in because it fixes this specific issue, but it seems like there are other places in the code that still use `get_num_assigned` where it might be more appropriate to use `get_num_collected` instead. So could you please review those places as well?

Yes, David. I thought of creating a new PR for that.