Fixed Grace Token Deductions to Use Display Name
MarkUsProject/Markus pull request #5630
Opened 2021-12-01 17:40 UTC by anoverga17

## Motivation and Context

This pull request fixes an issue whereby the results page which displays grace token deductions would show a user's first and last name in parentheses as opposed to their display name. 
In addition, the grace token deductions display for students was changed so that students can no longer see the grace token deductions for other group members (they can only see their own).

Fix for issue: #5610

## Your Changes

**Description**:
- Changed grace token deductions summary display to show a student's display name rather than their first and last name. 
- When logged in as a student, changed grace token deductions summary display to show only that student's deductions. 

**Type of change** (select all that apply):

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] Refactoring (internal change to codebase, without changing functionality)

## Testing

Manual testing was done to ensure the appropriate display name was shown. In addition, this testing was done whilst logged in as an admin, grader, and student roles to ensure only the relevant grace token deductions were being shown for a specific user (i.e. students could only see their own grace token deductions whilst admins and graders can see every group member's deductions). 

## Checklist

- [x] I have performed a self-review of my own code.
- [ ] I have fixed any Hound bot comments. 
- [ ] I have verified that the CI tests have passed. 
- [ ] I have reviewed the test coverage changes reported on Coveralls.

2021-12-01 20:59 UTC, mishaschwartz requested changes

2021-12-01 20:59 UTC, mishaschwartz commented on app/assets/javascripts/Components/Result/summary_panel.jsx
> +          <tr key={d["users.user_name"]} align="left">
Please don't add formatting as an attribute, this should be added as part of the css. In this case especially, the align attribute is not supported by html5 and should not be used.

For this PR, please remove it and we can discuss whether we should adjust the alignment in a different PR later on.

2021-12-01 20:59 UTC, mishaschwartz commented on app/controllers/results_controller.rb
> +        elsif current_user.student?
This is great! Please also add a few tests for this as well.

2021-12-07 13:14 UTC, mishaschwartz approved these changes

2021-12-07 13:14 UTC, mishaschwartz commented on spec/controllers/results_controller_spec.rb
> +      StudentMembership.create(user: partner,
This is fine for now but in the future, please use the factories when creating objects for tests:

```ruby
create :accepted_student_membership, user: partner, grouping: grouping
```

2021-12-08 16:11 UTC, david-yz-liu approved these changes
Thanks, @anoverga17!

2021-12-08 16:13 UTC, merged