update views for submissions
MarkUsProject/Markus pull request #5656
Opened 2021-12-08 21:07 UTC by pretendWhale

## Motivation and Context

- ensures that all submission views work as intended and all routing is up to date

## Your Changes

**Description**:

**Type of change** (select all that apply):

- [x] Other (please specify): multi-course markus rewrite

## Testing

## Questions and Comments (if applicable)

## Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have fixed any Hound bot comments. 

### Required documentation changes (if applicable)

2021-12-08 21:46 UTC, mishaschwartz requested changes
I'm still getting a bunch of errors when I try to access the repo browser page. Please have a look and fix those.

2021-12-08 21:46 UTC, mishaschwartz commented on app/assets/javascripts/Components/submission_table.jsx
>      }
There's another one to fix at line 204 (above)

2021-12-08 21:53 UTC, mishaschwartz commented on app/assets/javascripts/Components/submission_table.jsx
>      }
sorry I can't comment on the line directly

2021-12-08 23:27 UTC, pretendWhale commented
> I'm still getting a bunch of errors when I try to access the repo browser page. Please have a look and fix those.

Yeah, it turns out if you don't pass a course id prop to nested react components, those components don't know the current course id. Who would have thought. Should be fixed now

2021-12-09 13:45 UTC, mishaschwartz approved these changes

2021-12-09 13:45 UTC, merged