Fixed Bug with Editing Course Names
MarkUsProject/Markus pull request #6111
Opened 2022-07-19 23:19 UTC by anoverga17

## Motivation and Context

Currently, admins can edit 

## Your Changes

**Description**:

**Type of change** (select all that apply):

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)

## Testing

## Checklist

- [ ] I have performed a self-review of my own code.
- [ ] I have verified that the pre-commit.ci checks have passed. 
- [ ] I have verified that the CI tests have passed. 
- [ ] I have reviewed the test coverage changes reported on Coveralls. 
- [ ] I have added tests for my changes. 
- [ ] I have updated the Changelog.md file. 
- [ ] I have made changes to the documentation and linked to that pull request below. 

### Pull request to make documentation changes (if applicable)

2022-07-21 13:22 UTC, mishaschwartz requested changes
Looks good! just a few small changes to move some of the logic to the policy methods

2022-07-21 13:22 UTC, mishaschwartz commented on app/views/courses/_form.html.erb
> +                     readonly: !(@current_role.instructor? || @current_user.admin_user?) %>
please make this a policy method that is called with `allowed_to?`

2022-07-21 23:25 UTC, david-yz-liu approved these changes
@mishaschwartz please feel free to merge this one in after you've reviewed it again.

2022-07-22 13:06 UTC, mishaschwartz approved these changes

2022-07-22 13:07 UTC, merged