Group create api
MarkUsProject/Markus pull request #6834
Opened 2023-11-08 19:20 UTC by donny-wong

This API allows users to create a group for an assignment. 
HTTP Verb: POST
API: /api/courses/:course_id/assignments/:assignment_id/groups

## Motivation and Context
This API did not already exist, but that it existed for the application group controller with the method "new". 

## Your Changes
This API is created with the method "create", and it calls the newly created method, add_group_api, in the model "assignment". 

Once the group is created, the group information is returned.

**Type of change** (select all that apply):
- [x] New feature (non-breaking change which adds functionality)

## Testing
This was tested locally with postman. The parameter was sent via JSON:
{
    "new_group_name": "new group name 1"
}

## Checklist

- [x] I have performed a self-review of my own code.
- [ ] I have verified that the pre-commit.ci checks have passed. 
- [ ] I have verified that the CI tests have passed. 
- [ ] I have reviewed the test coverage changes reported on Coveralls. 
- [ ] I have added tests for my changes. 
- [ ] I have updated the Changelog.md file. 
- [ ] I have made changes to the documentation and linked to that pull request below.

2023-11-13 20:39 UTC, pretendWhale requested changes
@donny-wong I think it looks good, I left one comment about deleting an extraneous newline. We should look at adding the other verbs later

2023-11-13 20:39 UTC, pretendWhale commented on app/models/assignment.rb
> +
please delete this line

2023-11-13 21:08 UTC, pretendWhale approved these changes

2023-11-14 01:22 UTC, david-yz-liu approved these changes

2023-11-14 01:23 UTC, merged